SCREEN_WIDTH = 1280
SCREEN_HEIGHT = 720

ASTEROID_MIN_RADIUS = 20
ASTEROID_KINDS = 3
ASTEROID_SPAWN_RATE = 0.8  # seconds
ASTEROID_MAX_RADIUS = ASTEROID_MIN_RADIUS * ASTEROID_KINDS

player_radius = 20
player_turn_speed = 300
player_speed = 200

SHOT_RADIUS = 5
PLAYER_SHOT_SPEED = 500
PLAYER_SHOT_COOLDOWN = 0.4